default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: transfer_development
  username: imidsac
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: transfer_test
  username: imidsac
  password: <%= ENV["DATABASE_PASSWORD"] %>

staging:
 <<: *default
 database: transfer_staging
 username: imidsac
 password: <%= ENV["DATABASE_PASSWORD" ] %>

production:
 <<: *default
 database: transfer_production
 username: imidsac
 password: <%= ENV["DATABASE_PASSWORD" ] %>